### ISSUE TITLE
Usage with github action

### ISSUE THREAD

**Issue by grzesuav** [go-semantic-release/hooks-goreleaser#1]
Hi,

there isn't any documentation around that, how I can configure this plugin to be used in github action ?

**Comment by christophwitzko** [comment]
Hi @grzesuav, sorry for the late reply.

You can use set the `hooks` config option:
```yaml
- uses: go-semantic-release/action@v1
  with:
    hooks: goreleaser
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
I also added it to the documentation of the action https://github.com/go-semantic-release/action#arguments
