### ISSUE TITLE
Hook fails to build when unexpected configuration is found in `.goreleaser.yaml`

### ISSUE THREAD

**Issue by jamietanna** [go-semantic-release/hooks-goreleaser#4]
When using `goreleaser` version 1.22.1, and following https://goreleaser.com/quick-start/, running `goreleaser init`, we receive the following configuration:

```yaml
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
```

When we run `semantic-release` (version v2.29.0), we receive the following error:

```console
[go-semantic-release]: GoReleaser hook has failed: yaml: unmarshal errors:
  line 9: field version not found in type config.Project
[go-semantic-release]: stopping plugins...    
```

Ideally we would not fail for unexpected configuration, but I can imagine this may also be to protect us from running potentially newer version of `goreleaser` than we're expecting?
